image: Visual Studio 2022
version: 1.0.{build}
branches:
  only:
  - master

configuration: Release

before_build:
  - nuget restore 

build:
  verbosity: minimal
  project: TweetNaclSharp.sln

test:
  assemblies:
    - '**\*.Tests.dll'